{{/*
Manage model costs for standard all
*/}}
capacity: {{ .Values.inferenceSidecar.registerFeatures.capacity }}
{{- with .Values.inferenceSidecar.registerFeatures.modelCosts }}
model_costs:
  "*:diar_standard": {{ .diar }}
  "*:body_standard": {{ .body }}
  "*:audio_event_detection": {{ .audioEventDetection }}
  ar:am_ar_standard: {{ .am }}
  ba:am_ba_standard: {{ .am }}
  be:am_be_standard: {{ .am }}
  bg:am_bg_standard: {{ .am }}
  bn:am_bn_standard: {{ .am }}
  ca:am_ca_standard: {{ .am }}
  cmn:am_cmn_standard: {{ .am }}
  cmn_en:am_cmn_en_standard: {{ .am }}
  cs:am_cs_standard: {{ .am }}
  cy:am_cy_standard: {{ .am }}
  da:am_da_standard: {{ .am }}
  de:am_de_standard: {{ .am }}
  el:am_el_standard: {{ .am }}
  en:am_en_standard: {{ .am }}
  en_ms:am_en_ms_standard: {{ .am }}
  en_ta:am_en_ta_standard: {{ .am }}
  eo:am_eo_standard: {{ .am }}
  es:am_es_standard: {{ .am }}
  et:am_et_standard: {{ .am }}
  eu:am_eu_standard: {{ .am }}
  fa:am_fa_standard: {{ .am }}
  fi:am_fi_standard: {{ .am }}
  fr:am_fr_standard: {{ .am }}
  ga:am_ga_standard: {{ .am }}
  gl:am_gl_standard: {{ .am }}
  he:am_he_standard: {{ .am }}
  hi:am_hi_standard: {{ .am }}
  hr:am_hr_standard: {{ .am }}
  hu:am_hu_standard: {{ .am }}
  ia:am_ia_standard: {{ .am }}
  id:am_id_standard: {{ .am }}
  it:am_it_standard: {{ .am }}
  ja:am_ja_standard: {{ .am }}
  ko:am_ko_standard: {{ .am }}
  lt:am_lt_standard: {{ .am }}
  lv:am_lv_standard: {{ .am }}
  mn:am_mn_standard: {{ .am }}
  mr:am_mr_standard: {{ .am }}
  ms:am_ms_standard: {{ .am }}
  mt:am_mt_standard: {{ .am }}
  nl:am_nl_standard: {{ .am }}
  no:am_no_standard: {{ .am }}
  pl:am_pl_standard: {{ .am }}
  pt:am_pt_standard: {{ .am }}
  ro:am_ro_standard: {{ .am }}
  ru:am_ru_standard: {{ .am }}
  sk:am_sk_standard: {{ .am }}
  sl:am_sl_standard: {{ .am }}
  sv:am_sv_standard: {{ .am }}
  sw:am_sw_standard: {{ .am }}
  ta:am_ta_standard: {{ .am }}
  th:am_th_standard: {{ .am }}
  tl:am_tl_standard: {{ .am }}
  tr:am_tr_standard: {{ .am }}
  ug:am_ug_standard: {{ .am }}
  uk:am_uk_standard: {{ .am }}
  ur:am_ur_standard: {{ .am }}
  vi:am_vi_standard: {{ .am }}
  yue:am_yue_standard: {{ .am }}
  ar:ensemble_ar_standard: {{ .ensemble }}
  ba:ensemble_ba_standard: {{ .ensemble }}
  be:ensemble_be_standard: {{ .ensemble }}
  bg:ensemble_bg_standard: {{ .ensemble }}
  bn:ensemble_bn_standard: {{ .ensemble }}
  ca:ensemble_ca_standard: {{ .ensemble }}
  cmn:ensemble_cmn_standard: {{ .ensemble }}
  cmn_en:ensemble_cmn_en_standard: {{ .ensemble }}
  cs:ensemble_cs_standard: {{ .ensemble }}
  cy:ensemble_cy_standard: {{ .ensemble }}
  da:ensemble_da_standard: {{ .ensemble }}
  de:ensemble_de_standard: {{ .ensemble }}
  el:ensemble_el_standard: {{ .ensemble }}
  en:ensemble_en_standard: {{ .ensemble_en }}
  en_ms:ensemble_en_ms_standard: {{ .ensemble }}
  en_ta:ensemble_en_ta_standard: {{ .ensemble }}
  eo:ensemble_eo_standard: {{ .ensemble }}
  es:ensemble_es_standard: {{ .ensemble }}
  et:ensemble_et_standard: {{ .ensemble }}
  eu:ensemble_eu_standard: {{ .ensemble }}
  fa:ensemble_fa_standard: {{ .ensemble }}
  fi:ensemble_fi_standard: {{ .ensemble }}
  fr:ensemble_fr_standard: {{ .ensemble }}
  ga:ensemble_ga_standard: {{ .ensemble }}
  gl:ensemble_gl_standard: {{ .ensemble }}
  he:ensemble_he_standard: {{ .ensemble }}
  hi:ensemble_hi_standard: {{ .ensemble }}
  hr:ensemble_hr_standard: {{ .ensemble }}
  hu:ensemble_hu_standard: {{ .ensemble }}
  ia:ensemble_ia_standard: {{ .ensemble }}
  id:ensemble_id_standard: {{ .ensemble }}
  it:ensemble_it_standard: {{ .ensemble }}
  ja:ensemble_ja_standard: {{ .ensemble }}
  ko:ensemble_ko_standard: {{ .ensemble }}
  lt:ensemble_lt_standard: {{ .ensemble }}
  lv:ensemble_lv_standard: {{ .ensemble }}
  mn:ensemble_mn_standard: {{ .ensemble }}
  mr:ensemble_mr_standard: {{ .ensemble }}
  ms:ensemble_ms_standard: {{ .ensemble }}
  mt:ensemble_mt_standard: {{ .ensemble }}
  nl:ensemble_nl_standard: {{ .ensemble }}
  no:ensemble_no_standard: {{ .ensemble }}
  pl:ensemble_pl_standard: {{ .ensemble }}
  pt:ensemble_pt_standard: {{ .ensemble }}
  ro:ensemble_ro_standard: {{ .ensemble }}
  ru:ensemble_ru_standard: {{ .ensemble }}
  sk:ensemble_sk_standard: {{ .ensemble }}
  sl:ensemble_sl_standard: {{ .ensemble }}
  sv:ensemble_sv_standard: {{ .ensemble }}
  sw:ensemble_sw_standard: {{ .ensemble }}
  ta:ensemble_ta_standard: {{ .ensemble }}
  th:ensemble_th_standard: {{ .ensemble }}
  tl:ensemble_tl_standard: {{ .ensemble }}
  tr:ensemble_tr_standard: {{ .ensemble }}
  ug:ensemble_ug_standard: {{ .ensemble }}
  ur:ensemble_ur_standard: {{ .ensemble }}
  uk:ensemble_uk_standard: {{ .ensemble }}
  vi:ensemble_vi_standard: {{ .ensemble }}
  yue:ensemble_yue_standard: {{ .ensemble }}
{{- end }}
{{- with .Values.inferenceSidecar.registerFeatures.additionalModelCosts }}
  {{- . | toYaml | nindent 2 }}
{{- end }}
